#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function fail(msg) {
  throw new Error(`CITY REQUEST ARGS FAIL: ${msg}`);
}

function getArg(name, fallback = '') {
  const prefix = `--${name}=`;
  const raw = process.argv.find((arg) => arg.startsWith(prefix));
  return raw ? raw.slice(prefix.length) : fallback;
}

function normalizeBool(value) {
  const v = String(value || '').trim().toLowerCase();
  return v === 'true' || v === '1' || v === 'yes';
}

function slugifyCity(cityName, stateCode) {
  const city = String(cityName || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  const state = String(stateCode || '').trim().toLowerCase();
  return `${city}-${state}`;
}

const outputPath = getArg('output');
const vertical = getArg('vertical');
const stateCode = String(getArg('state_code')).trim().toUpperCase();
const cityName = String(getArg('city_name')).trim();
const citySlug = getArg('city_slug') || slugifyCity(cityName, stateCode);
const marketLabel = getArg('market_label') || `${cityName}, ${stateCode}`;
const sponsorKey = getArg('sponsor_key');
const intendedPackage = getArg('intended_package', 'statewide');
const isBaseIncluded = normalizeBool(getArg('is_base_included'));
const isExtraCity = normalizeBool(getArg('is_extra_city'));
const requestedBySponsor = normalizeBool(getArg('requested_by_sponsor', 'true'));
const notes = getArg('notes', 'Generated by GitHub Action city request workflow.');

if (!outputPath) fail('missing --output');
if (!vertical || !stateCode || !cityName) fail('missing required inputs: vertical, state_code, city_name');
if ((isBaseIncluded && isExtraCity) || (!isBaseIncluded && !isExtraCity)) {
  fail('city request must be exactly one of base or extra');
}

const payload = {
  template_version: "CITY_REQUEST_TEMPLATE_V1",
  purpose: "Generated from structured inputs for GitHub workflow city creation.",
  fields_required: [
    "vertical",
    "state_code",
    "city_name",
    "city_slug",
    "market_label",
    "intended_package",
    "is_base_included",
    "is_extra_city"
  ],
  requests: [
    {
      vertical,
      state_code: stateCode,
      city_name: cityName,
      city_slug: citySlug,
      market_label: marketLabel,
      requested_by_sponsor: requestedBySponsor,
      sponsor_key: sponsorKey || undefined,
      intended_package: intendedPackage,
      is_base_included: isBaseIncluded,
      is_extra_city: isExtraCity,
      notes
    }
  ]
};

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, JSON.stringify(payload, null, 2) + '\n', 'utf8');
console.log(JSON.stringify({ output: outputPath, city_slug: citySlug, state_code: stateCode }, null, 2));
