#!/usr/bin/env node
/**
 * Emits dist/_redirects so friendly paths resolve:
 *  - /sitemap   -> /sitemap.xml
 *  - /indexnow  -> /indexnow.txt
 * Also supports .well-known/ for indexnow key discovery.
 *
 * Plus the active pack's `legacyRedirects` ([{ from, to }] in its page set): retired URLs that
 * search engines still hold (Bing Webmaster 404 list, 25 Sep 2026) sent with a 301 to the live
 * page on the same topic. Fails before write if a target is not a page this build produced, is
 * the homepage, or if a `from` path would shadow a live page. Guarded after the build by
 * scripts/validation/legacy_redirects_contract.js.
 *
 * Works on Cloudflare Pages + Netlify-style redirects.
 */
const fs = require("fs");
const path = require("path");

function ensureDir(p) { fs.mkdirSync(p, { recursive: true }); }

function loadLegacyRedirects(distDir) {
  const sitePath = path.join(process.cwd(), "data", "site.json");
  if (!fs.existsSync(sitePath)) return [];
  const site = JSON.parse(fs.readFileSync(sitePath, "utf8"));
  const pageSetFile = String(site.pageSetFile || "").trim();
  if (!pageSetFile) return [];
  const abs = path.isAbsolute(pageSetFile) ? pageSetFile : path.join(process.cwd(), pageSetFile);
  if (!fs.existsSync(abs)) throw new Error("redirects_emit: page set not found: " + pageSetFile);
  const pageSet = JSON.parse(fs.readFileSync(abs, "utf8"));
  const rows = Array.isArray(pageSet.legacyRedirects) ? pageSet.legacyRedirects : [];
  const problems = [];
  const out = [];
  for (const row of rows) {
    const from = String((row && row.from) || "").trim().replace(/\/+$/, "");
    const to = String((row && row.to) || "").trim();
    if (!from.startsWith("/") || from === "") problems.push("bad from: " + JSON.stringify(row));
    if (!/^\/[^\s]*\/$/.test(to)) problems.push("to must be a site path with a trailing slash: " + JSON.stringify(row));
    if (to === "/" || to === "") problems.push("never redirect to the homepage: " + JSON.stringify(row));
    const target = path.join(distDir, to.replace(/^\/+/, ""), "index.html");
    if (!fs.existsSync(target)) problems.push("target is not a built page: " + to);
    const shadow = path.join(distDir, from.replace(/^\/+/, ""), "index.html");
    if (fs.existsSync(shadow)) problems.push("from path is a live page and would be shadowed: " + from);
    out.push(from + " " + to + " 301", from + "/ " + to + " 301");
  }
  if (problems.length) throw new Error("redirects_emit: invalid legacyRedirects in " + pageSetFile + "\n  " + problems.join("\n  "));
  return out;
}

function main() {
  const distDir = path.join(process.cwd(), "dist");
  ensureDir(distDir);
  const legacy = loadLegacyRedirects(distDir);

  const lines = [
    "# Generated by scripts/redirects_emit.js",
    "/sitemap /sitemap.xml 301",
    "/sitemap.xml /sitemap.xml 200",
    "/indexnow /indexnow.txt 301",
    "/indexnow.txt /indexnow.txt 200",
    "/.well-known/indexnow.txt /indexnow.txt 301",
    ...(legacy.length ? ["# Retired URLs -> live page on the same topic (page set legacyRedirects)"].concat(legacy) : []),
    ""
  ];

  fs.writeFileSync(path.join(distDir, "_redirects"), lines.join("\n"), "utf8");
  console.log("redirects_emit: wrote dist/_redirects");
}

main();
