#!/usr/bin/env node
/**
 * Emits dist/_redirects so friendly paths resolve:
 *  - /sitemap   -> /sitemap.xml
 *  - /indexnow  -> /indexnow.txt
 * Also supports .well-known/ for indexnow key discovery.
 *
 * Works on Cloudflare Pages + Netlify-style redirects.
 */
const fs = require("fs");
const path = require("path");

function ensureDir(p) { fs.mkdirSync(p, { recursive: true }); }

function main() {
  const distDir = path.join(process.cwd(), "dist");
  ensureDir(distDir);

  const lines = [
    "# Generated by scripts/redirects_emit.js",
    "/sitemap /sitemap.xml 301",
    "/sitemap.xml /sitemap.xml 200",
    "/indexnow /indexnow.txt 301",
    "/indexnow.txt /indexnow.txt 200",
    "/.well-known/indexnow.txt /indexnow.txt 301",
    ""
  ];

  fs.writeFileSync(path.join(distDir, "_redirects"), lines.join("\n"), "utf8");
  console.log("redirects_emit: wrote dist/_redirects");
}

main();
