#!/usr/bin/env node
/**
 * Fails the build on the three ways this fan-out goes wrong.
 *
 *   1. A sitemap URL that does not render.
 *   2. A city page admitted to a sitemap with no research file behind it - a
 *      page that names a city and says nothing about it, generated by
 *      interpolating the slug into a fixed prose template.
 *   3. Any measured-demand claim this repo cannot support.
 *
 * Check 2 is scoped to new cities via a sealed baseline. 197 of the 221 non-PI
 * city pages already render from the template; failing on all of them would
 * produce a validator someone switches off rather than one that holds. What it
 * blocks is the 198th.
 *
 * Check 3 reports rather than blocks, because there is nothing to check
 * against: a search across data/ for volume, keyword_difficulty or impressions
 * returns two prose false positives and nothing else. City selection is a
 * hand-typed slug list and the page count is cities x per-city templates. The
 * one demand-adjacent path, the cross-repo pull from citation-velocity, is
 * dormant - promotion_candidates.source.json is an empty array and
 * reference_registry.json records promoted_ids: 0.
 */
const fs = require('fs');
const path = require('path');
const { researchedSlugs, verticals } = require('../helpers/research_coverage');

const ROOT = path.resolve(__dirname, '..', '..');
const DIST = path.join(ROOT, 'dist');
const BASELINE = path.join(ROOT, 'data', 'reference', 'pre_gate_city_baseline.json');

const errors = [];
const notes = [];

// --- coverage, per vertical -------------------------------------------------
const coverage = {};
const unresearched = [];
for (const v of verticals()) {
  const citiesFile = path.join(ROOT, 'data', 'page_sets', 'examples', `cities_${v}_v1.json`);
  if (!fs.existsSync(citiesFile)) continue;
  const cities = JSON.parse(fs.readFileSync(citiesFile, 'utf8'));
  const researched = researchedSlugs(v);
  coverage[v] = { total: cities.length, researched: researched.size };
  for (const c of cities) {
    const slug = c.slug || c;
    if (!researched.has(slug)) unresearched.push(`${v}/${slug}`);
  }
}

if (process.argv.includes('--seed-baseline')) {
  fs.mkdirSync(path.dirname(BASELINE), { recursive: true });
  fs.writeFileSync(BASELINE, JSON.stringify({
    note: 'City pages that were already rendering from the slug-interpolated template when the research gate was installed. Exempt from the gate; any city added after this needs a research file under data/city_content/<vertical>/<slug>.json. Do not add entries here to get past the gate - add the research.',
    sealed_at: new Date().toISOString().slice(0, 10),
    count: unresearched.length,
    cities: unresearched.slice().sort(),
  }, null, 2) + '\n');
  console.log(`Sealed pre-gate city baseline: ${unresearched.length} unresearched cities.`);
  process.exit(0);
}

// --- 1. sitemap parity ------------------------------------------------------
const sitemapDir = fs.existsSync(DIST) ? DIST : null;
if (!sitemapDir) {
  notes.push('no dist/ on disk; run `npm run build` first');
} else {
  const locs = new Set();
  for (const f of fs.readdirSync(DIST).filter((n) => /^sitemap.*\.xml$/.test(n))) {
    for (const m of fs.readFileSync(path.join(DIST, f), 'utf8').matchAll(/<loc>([^<]+)<\/loc>/g)) locs.add(m[1]);
  }
  const missing = [];
  for (const loc of locs) {
    let p;
    try { p = new URL(loc).pathname; } catch { p = loc; }
    const rel = p.replace(/^\//, '').replace(/\/$/, '');
    const candidates = rel === '' ? ['index.html'] : [rel, `${rel}.html`, path.join(rel, 'index.html')];
    if (!candidates.some((c) => fs.existsSync(path.join(DIST, c)))) missing.push(p);
  }
  if (missing.length) errors.push(`${missing.length} sitemap URL(s) do not render, e.g. ${missing.slice(0, 5).join(', ')}`);
  else notes.push(`sitemap: ${locs.size} URLs, all render`);
}

// --- 2. no new city page without research -----------------------------------
if (!fs.existsSync(BASELINE)) {
  notes.push('no pre-gate baseline; run this validator once with --seed-baseline');
} else {
  const known = new Set(JSON.parse(fs.readFileSync(BASELINE, 'utf8')).cities || []);
  const added = unresearched.filter((c) => !known.has(c));
  if (added.length) {
    errors.push(
      `${added.length} city page(s) added after the research gate have no file under data/city_content/. ` +
      `They will render the slug-interpolated template, which names the city and says nothing about it:\n  ` +
      added.slice(0, 20).join('\n  ')
    );
  }
  notes.push(
    `research coverage: ${JSON.stringify(coverage)}. ${known.size} pre-gate cities render from the template - ` +
    `not a build failure, but each is a page competing for a city query on boilerplate. Retirement or research candidates.`
  );
  // Which of them can actually BE researched, measured rather than assumed, so
  // the next person does not burn a day rediscovering it or - worse - fill the
  // pages with invented figures to make the number move.
  //
  // Of the nine sources in data/research/costs/sources.json, exactly two carry
  // per-state or per-city grain, and both are Medicare files. USCIS G-1055, the
  // USCIS form pages, ADA HPI, FDA compounding, IRS Pub 4345 and the federal
  // court fee schedule are all national-only: they can make a page more
  // truthful, but they cannot make one city's page differ from the next.
  //
  //   neuro, trt   researchable, and now researched - Medicare covers those
  //                services, so CMS publishes state figures for them.
  //   pi           researched from state statute and fee data.
  //   dentistry    NOT researchable from CMS. State coverage on the dental
  //                codes is D7140 9, D7210 9, 41899 13, 21248 5, D7220 and
  //                D7230 none, because Medicare largely excludes routine
  //                dental. The repo's own Bing research already refused the
  //                city-cost axis on this evidence. It is not a gap, it is an
  //                absence.
  //   uscis_medical  NOT researchable from any registered source. No per-city
  //                grain exists, the civil surgeon exam fee is set by the
  //                individual surgeon and is not published, and USCIS filing
  //                fees are national.
  //
  // So those remaining cities need an architecture decision about whether
  // per-city pages should exist for a subject with no per-city facts. They do
  // not need more research, and they must not be filled in.
  notes.push(
    'RESEARCHABLE: neuro and trt via CMS state data, pi via state statute data. '
    + 'NOT RESEARCHABLE from any registered source: the remaining dentistry cities '
    + '(CMS covers at most 9 states on the dental codes; Medicare excludes routine dental) '
    + 'and the remaining uscis_medical cities (no per-city grain exists anywhere; the civil '
    + 'surgeon exam fee is unpublished). Those need an architecture decision, not more research.'
  );
}

// --- 3. demand --------------------------------------------------------------
notes.push(
  'NOT MEASURED: no volume, keyword_difficulty, or impression figure exists anywhere under data/. ' +
  'City selection is a hand-typed slug list and the page count is cities x per-city templates. ' +
  'The cross-repo pull from citation-velocity is dormant (promoted_ids: 0).'
);

for (const n of notes) console.log(`note: ${n}`);
if (errors.length) {
  console.error('validate:demand-backed-pages FAILED');
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}
console.log('validate:demand-backed-pages OK');
